"""Version information."""
__title__ = "databricks-api"
__description__ = "Databricks API client interface."
__url__ = "https://github.com/crflynn/databricks-api"
__version__ = "0.1.0"
__author__ = "Christopher Flynn"
__author_email__ = "crf204@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Christopher Flynn"
